apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    proj: roboshop
    app: frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      proj: roboshop
      app: frontend
      tier: frontend
  template:
    metadata:
      labels:
        proj: roboshop
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: gangadhar3011/frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
  labels:
    proj: roboshop
    app: frontend
    tier: frontend
spec:
  type: LoadBalancer 
  selector:
    proj: roboshop
    app: frontend
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80