apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    proj: roboshop
    app: payment
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      proj: roboshop
      app: payment
      tier: backend
  template:
    metadata:
      labels:
        proj: roboshop
        app: payment
        tier: backend
    spec:
      containers:
      - name: payment
        image: gangadhar3011/payment:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: payment-config
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    proj: roboshop
    app: payment
    tier: backend
spec:
  type: ClusterIP 
  selector:
    proj: roboshop
    app: payment
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: roboshop
data:
  CART_HOST: cart
  CART_PORT: "8080"
  USER_HOST: user
  USER_PORT: "8080"
  AMQP_HOST: rabbitmq
  AMQP_USER: roboshop
  AMQP_PASS: roboshop123
