apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    proj: roboshop
    app: cart
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      proj: roboshop
      app: cart
      tier: backend
  template:
    metadata:
      labels:
        proj: roboshop
        app: cart
        tier: backend
    spec:
      containers:
      - name: cart
        image: gangadhar3011/cart:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cart-config
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    proj: roboshop
    app: cart
    tier: backend
spec:
  type: ClusterIP 
  selector:
    proj: roboshop
    app: cart
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"