apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    proj: roboshop
    app: shipping
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      proj: roboshop
      app: shipping
      tier: backend
  template:
    metadata:
      labels:
        proj: roboshop
        app: shipping
        tier: backend
    spec:
      containers:
      - name: shipping
        image: gangadhar3011/shipping:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: shipping-config
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    proj: roboshop
    app: shipping
    tier: backend
spec:
  type: ClusterIP 
  selector:
    proj: roboshop
    app: shipping
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
  namespace: roboshop
data:
  CART_ENDPOINT: cart:8080
  DB_HOST: mysql