apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    proj: roboshop
    app: mongodb
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      proj: roboshop
      app: mongodb
      tier: database
  template:
    metadata:
      labels:
        proj: roboshop
        app: mongodb
        tier: database
    spec:
      containers:
      - name: mongodb
        image: gangadhar3011/mongodb:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    proj: roboshop
    app: mongodb
    tier: database
spec:
  type: ClusterIP 
  selector:
    proj: roboshop
    app: mongodb
    tier: database
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017 