apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    proj: roboshop
    app: mysql
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      proj: roboshop
      app: mysql
      tier: database
  template:
    metadata:
      labels:
        proj: roboshop
        app: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: gangadhar3011/mysql:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    proj: roboshop
    app: mysql
    tier: database
spec:
  type: ClusterIP 
  selector:
    proj: roboshop
    app: mysql
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306 