apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    proj: roboshop
    app: user
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      proj: roboshop
      app: user
      tier: backend
  template:
    metadata:
      labels:
        proj: roboshop
        app: user
        tier: backend
    spec:
      containers:
      - name: user
        image: gangadhar3011/user:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: user-config
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    proj: roboshop
    app: user
    tier: backend
spec:
  type: ClusterIP 
  selector:
    proj: roboshop
    app: user
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: roboshop
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"